Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/RaiseArgs:
  Enabled: false
