Rails:
  Enabled: true

AllCops:
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.4

  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
  DisplayCopNames: true

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BlockComments:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/RaiseArgs:
  Enabled: false

Style/AndOr:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false
