default: &default
  adapter: postgresql
  timeout: 5000
  pool: <%= ENV.fetch("DB_POOL_SIZE", 10) %>
  username: <%= ENV.fetch("DB_USERNAME", "postgres") %>
  password: <%= ENV.fetch("DB_PASSWORD", "budgetr_password") %>
  host: <%= ENV.fetch("DB_ADDRESS", "postgres") %>

development: &development
  <<: *default
  password: <%= ENV.fetch("DB_PASSWORD", "derigible-password") %>
  database: <%= ENV.fetch("DB_NAME", "budgetr_dev") %>

local_development:
  <<: *default
  password: <%= ENV.fetch("DB_PASSWORD", "derigible-password") %>
  username: <%= ENV.fetch("DB_USERNAME", "derigible") %>
  database: <%= ENV.fetch("DB_NAME", "budgetr_dev") %>
  host: <%= ENV.fetch("DB_ADDRESS", "localhost") %>

demos:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "budgetr_demos") %>

development_server:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "budgetr_development_server") %>

staging:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "budgetr_staging") %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *development
  database: "budgetr_test"

# Database credentials should never be hard coded and Elastic Beanstalk
# makes managing environment variables quite simple.
production:
  <<: *default
  pool: <%= ENV.fetch("DB_POOL_SIZE", 30) %>
  database: <%= ENV.fetch("DB_NAME", "budgetr_production") %>
