# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 430b5a64931fe34cd2f9a162a46d948e3c19d36d77c157fa135e59b28224c131efa9c04b02d91bfc7adb7707299fbb709ef657a1c1cc34ebb303af4c06dde4e4

test:
  secret_key_base: 90a43396668e84687925a43fb47acbe5b3d1294467e64acfac6ed9492d2fc80b246558e1ae0dbf2efd6e3d8704c757674f45f317085de78b8f8f1f39837cfe54

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
