import { closeSidebar, openSidebar } from './sidebar'
import { navigateTo } from './navigation'
import {
  submitUserCredentials,
  submitForgotEmail,
  setAlertMessage,
  setAuthTokens,
  createUser,
  setUserInfo,
  logout,
  submitResetPassword
} from './auth'
import {
  setTodosRetrieved,
  createTodo,
  updateTodo,
  removeTodo,
  deleteTodo,
  setTodos,
  fetchTodos,
  shareTodo,
  fetchTodoSharedWith,
  setTodoSharedWith,
  fetchTodoShareableWith,
  setTodoShareableWith,
  updateTodoPreferences,
  snoozeTodo,
  archiveTodo
} from './todo'
import {
  setTags,
  setTagsRetrieved,
  fetchTags,
  createTag,
  tagEntity,
  removeTag,
  setSelectedTags
} from './tag'
import {
  setNotes,
  setNotesRetrieved,
  fetchNotes,
  fetchNote,
  createNote,
  updateNote,
  deleteNote,
  removeNote,
  shareNote,
  setNoteSharedWith,
  setNoteShareableWith,
  fetchNoteSharedWith,
  fetchNoteShareableWith,
  updateNotePreferences,
  snoozeNote,
  archiveNote
} from './note'
import {
  setContacts,
  setContactsRetrieved,
  fetchContacts,
  createContact
} from './contact'
import {
  setPreferences,
  fetchPreference,
  updatePreference
} from './preferences'

export {
  navigateTo,
  closeSidebar,
  openSidebar,
  createUser,
  submitUserCredentials,
  setAuthTokens,
  setUserInfo,
  createTodo,
  updateTodo,
  deleteTodo,
  removeTodo,
  setTodos,
  setTodosRetrieved,
  fetchTodos,
  setTags,
  setTagsRetrieved,
  fetchTags,
  createTag,
  tagEntity,
  removeTag,
  setNotes,
  setNotesRetrieved,
  fetchNotes,
  fetchNote,
  createNote,
  updateNote,
  deleteNote,
  removeNote,
  logout,
  submitForgotEmail,
  setAlertMessage,
  submitResetPassword,
  shareNote,
  shareTodo,
  setContacts,
  setContactsRetrieved,
  fetchContacts,
  createContact,
  fetchTodoSharedWith,
  setTodoSharedWith,
  fetchTodoShareableWith,
  setTodoShareableWith,
  setNoteSharedWith,
  setNoteShareableWith,
  fetchNoteSharedWith,
  fetchNoteShareableWith,
  setPreferences,
  updatePreference,
  fetchPreference,
  updateTodoPreferences,
  updateNotePreferences,
  setSelectedTags,
  snoozeTodo,
  snoozeNote,
  archiveTodo,
  archiveNote
}
