// @flow

export type ComponentActionType = {
  type: string,
  payload: string
}

export const ALERT_ERROR_ALERT = 'ALERT_ERROR_ALERT'
export const ALERT_LOGIN_ALERT = 'ALERT_LOGIN_ALERT'

export const ENTITY_ENTITY_API_ACTION_SUCCESS = 'ENTITY_ENTITY_API_ACTION_SUCCESS'
export const ENTITY_SET_ENTITY_API_ACTION_STATE = 'ENTITY_SET_ENTITY_API_ACTION_STATE'

export const FETCH_STATE_IN_PROGRESS = 'FETCH_STATE_IN_PROGRESS'
export const FETCH_STATE_SUCCESS = 'FETCH_STATE_SUCCESS'
export const FETCH_STATE_ERROR = 'FETCH_STATE_ERROR'
export const FETCH_STATE_WAITING = 'FETCH_STATE_WAITING'

export const ENTITY_ACTION_CREATE = 'ENTITY_ACTION_CREATE'
export const ENTITY_ACTION_READ = 'ENTITY_ACTION_READ'
export const ENTITY_ACTION_UPDATE = 'ENTITY_ACTION_UPDATE'
export const ENTITY_ACTION_DESTROY = 'ENTITY_ACTION_DESTROY'
export const ENTITY_ACTION_LIST = 'ENTITY_ACTION_LIST'
export const ENTITY_ACTION_ARCHIVE = 'ENTITY_ACTION_ARCHIVE'
export const ENTITY_ACTION_UNARCHIVE = 'ENTITY_ACTION_UNARCHIVE'
export const ENTITY_ACTION_SNOOZE = 'ENTITY_ACTION_SNOOZE'
export const ENTITY_ACTION_UNSNOOZE = 'ENTITY_ACTION_UNSNOOZE'
export const ENTITY_ACTION_TAG = 'ENTITY_ACTION_TAG'
export const ENTITY_ACTION_UNTAG = 'ENTITY_ACTION_UNTAG'
export const ENTITY_ACTION_SHARE = 'ENTITY_ACTION_SHARE'
export const ENTITY_ACTION_UNSHARE = 'ENTITY_ACTION_UNSHARE'
export const ENTITY_ACTION_SHARED_WITH = 'ENTITY_ACTION_SHARED_WITH'
export const ENTITY_ACTION_SHAREABLE_WITH = 'ENTITY_ACTION_SHAREABLE_WITH'
export const ENTITY_ACTION_UPDATE_PREFERENCES = 'ENTITY_ACTION_UPDATE_PREFERENCES'
