export const EVENTS_SET = 'EVENTS_SET'
export const EVENTS_SHOW_MORE = 'EVENTS_SHOW_MORE'

export const HISTORY_SET_SORT_BY_KEY = 'HISTORY_SET_SORT_BY_KEY'

export const DASHBOARD_SET_FILTER_BY = 'DASHBOARD_SET_FILTER_BY'
export const DASHBOARD_SET_LOOKUP_TERM = 'DASHBOARD_SET_LOOKUP_TERM'
export const DASHBOARD_SET_LOOKUP_PARAM = 'DASHBOARD_SET_LOOKUP_PARAM'
export const DASHBOARD_EVENTS_RETRIEVED = 'DASHBOARD_EVENTS_RETRIEVED'

export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'

export const NAVIGATE_TO = 'NAVIGATE_TO'
export const NAVIGATE_WITHOUT_ROUTING = 'NAVIGATE_WITHOUT_ROUTING'
export const GO_BACK = 'GO_BACK'
export const UPDATE_PATH = 'UPDATE_PATH'

export const CATEGORIES_RETRIEVED = 'CATEGORIES_RETRIEVED'
export const CATEGORIES_SET = 'CATEGORIES_SET'
export const CATEGORY_EVENTS_RETRIEVED = 'CATEGORY_EVENTS_RETRIEVED'

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_AUTH_ALERT_MESSAGE = 'SET_AUTH_ALERT_MESSAGE'

export const SET_SPINNER_OVERLAY = 'SET_SPINNER_OVERLAY'
export const UNSET_SPINNER_OVERLAY = 'UNSET_SPINNER_OVERLAY'

export const TODOS_SET_RETRIEVED = 'TODOS_SET_RETRIEVED'
export const TODOS_REMOVE_TODO = 'TODOS_REMOVE_TODO'
export const TODOS_SET_TODOS = 'TODOS_SET_TODOS'
export const TODOS_SET_TODO_SHARED_WITH = 'TODOS_SET_TODO_SHARED_WITH'
export const TODOS_SET_TODO_SHAREABLE_WITH = 'TODOS_SET_TODO_SHAREABLE_WITH'

export const TAGS_SET_RETRIEVED = 'TAGS_SET_RETRIEVED'
export const TAGS_SET_TAGS = 'TAGS_SET_TAGS'
export const TAGS_SET_SELECTED_TAGS = 'TAGS_SET_SELECTED_TAGS'

export const NOTES_SET_NOTES = 'NOTES_SET_NOTES'
export const NOTES_SET_RETRIEVED = 'NOTES_SET_RETRIEVED'
export const NOTES_REMOVE_NOTE = 'NOTES_REMOVE_NOTE'
export const NOTES_SET_NOTE_SHARED_WITH = 'NOTES_SET_NOTE_SHARED_WITH'
export const NOTES_SET_NOTE_SHAREABLE_WITH = 'NOTES_SET_NOTE_SHAREABLE_WITH'

export const CONTACTS_SET_CONTACTS = 'CONTACTS_SET_CONTACTS'
export const CONTACTS_SET_RETRIEVED = 'CONTACTS_SET_RETRIEVED'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const USERS_SET_RETRIEVED = 'USERS_SET_RETRIEVED'
export const USERS_SET_USERS = 'USERS_SET_USERS'

export const PREFERENCES_SET_PREFERENCES = 'PREFERENCES_SET_PREFERENCES'
