export const CLOSE_SIDEBAR = 'CLOSE_SIDEBAR'
export const OPEN_SIDEBAR = 'OPEN_SIDEBAR'

export const NAVIGATE_TO = 'NAVIGATE_TO'

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
export const SET_USER_INFO = 'SET_USER_INFO'
export const SET_AUTH_ALERT_MESSAGE = 'SET_AUTH_ALERT_MESSAGE'

export const TODOS_SET_RETRIEVED = 'TODOS_SET_RETRIEVED'
export const TODOS_REMOVE_TODO = 'TODOS_REMOVE_TODO'
export const TODOS_SET_TODOS = 'TODOS_SET_TODOS'
export const TODOS_SET_TODO_SHARED_WITH = 'TODOS_SET_TODO_SHARED_WITH'
export const TODOS_SET_TODO_SHAREABLE_WITH = 'TODOS_SET_TODO_SHAREABLE_WITH'

export const TAGS_SET_RETRIEVED = 'TAGS_SET_RETRIEVED'
export const TAGS_SET_TAGS = 'TAGS_SET_TAGS'
export const TAGS_SET_SELECTED_TAGS = 'TAGS_SET_SELECTED_TAGS'

export const NOTES_SET_NOTES = 'NOTES_SET_NOTES'
export const NOTES_SET_RETRIEVED = 'NOTES_SET_RETRIEVED'
export const NOTES_REMOVE_NOTE = 'NOTES_REMOVE_NOTE'
export const NOTES_SET_NOTE_SHARED_WITH = 'NOTES_SET_NOTE_SHARED_WITH'
export const NOTES_SET_NOTE_SHAREABLE_WITH = 'NOTES_SET_NOTE_SHAREABLE_WITH'

export const CONTACTS_SET_CONTACTS = 'CONTACTS_SET_CONTACTS'
export const CONTACTS_SET_RETRIEVED = 'CONTACTS_SET_RETRIEVED'

export const AUTH_LOGOUT = 'AUTH_LOGOUT'

export const USERS_SET_RETRIEVED = 'USERS_SET_RETRIEVED'
export const USERS_SET_USERS = 'USERS_SET_USERS'

export const PREFERENCES_SET_PREFERENCES = 'PREFERENCES_SET_PREFERENCES'

// NEW CONSTANTS
export const ALERT_ERROR_ALERT = 'ALERT_ERROR_ALERT'
export const ALERT_LOGIN_ALERT = 'ALERT_LOGIN_ALERT'

export const ENTITY_ENTITY_API_ACTION_SUCCESS = 'ENTITY_ENTITY_API_ACTION_SUCCESS'
export const ENTITY_SET_ENTITY_API_ACTION_STATE = 'ENTITY_SET_ENTITY_API_ACTION_STATE'

export const FETCH_STATE_IN_PROGRESS = 'FETCH_STATE_IN_PROGRESS'
export const FETCH_STATE_SUCCESS = 'FETCH_STATE_SUCCESS'
export const FETCH_STATE_ERROR = 'FETCH_STATE_ERROR'
export const FETCH_STATE_WAITING = 'FETCH_STATE_WAITING'

export const ENTITY_ACTION_CREATE = 'ENTITY_ACTION_CREATE'
export const ENTITY_ACTION_READ = 'ENTITY_ACTION_READ'
export const ENTITY_ACTION_UPDATE = 'ENTITY_ACTION_UPDATE'
export const ENTITY_ACTION_DESTROY = 'ENTITY_ACTION_DESTROY'
export const ENTITY_ACTION_LIST = 'ENTITY_ACTION_LIST'
export const ENTITY_ACTION_ARCHIVE = 'ENTITY_ACTION_ARCHIVE'
export const ENTITY_ACTION_UNARCHIVE = 'ENTITY_ACTION_UNARCHIVE'
export const ENTITY_ACTION_SNOOZE = 'ENTITY_ACTION_SNOOZE'
export const ENTITY_ACTION_UNSNOOZE = 'ENTITY_ACTION_UNSNOOZE'
export const ENTITY_ACTION_TAG = 'ENTITY_ACTION_TAG'
export const ENTITY_ACTION_UNTAG = 'ENTITY_ACTION_UNTAG'
export const ENTITY_ACTION_SHARE = 'ENTITY_ACTION_SHARE'
export const ENTITY_ACTION_UNSHARE = 'ENTITY_ACTION_UNSHARE'
export const ENTITY_ACTION_SHARED_WITH = 'ENTITY_ACTION_SHARED_WITH'
export const ENTITY_ACTION_SHAREABLE_WITH = 'ENTITY_ACTION_SHAREABLE_WITH'
export const ENTITY_ACTION_UPDATE_PREFERENCES = 'ENTITY_ACTION_UPDATE_PREFERENCES'
